/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payment.management.system;

import java.awt.event.*;
import java.beans.Statement;
import java.io.FileOutputStream;
import java.sql.*;
import javax.swing.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.lang.String;
import com.lowagie.text.*;
import com.lowagie.text.Document;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfTable;
import com.lowagie.text.pdf.PdfWriter;
import com.pdfjet.*;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.text.MessageFormat;
import java.awt.print.*;
import java.io.BufferedOutputStream;
import java.io.File;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
/**
 *
 * @author ESeries
 */
public class MainPage extends javax.swing.JFrame implements ActionListener {
        //private JFrame frame;
        Connection cnn;
	PreparedStatement pst;
	ResultSet res;
        ResultSetMetaData rsmd;
	String url="jdbc:mysql://localhost/payment?user=root&password=eimon";
        //boolean selected;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        //frame=new JFrame();
        //frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //frame.setVisible(true);
        //frame.setResizable(false);
        initComponents();
        yearCombo();
        rollNoCombo();
        feeCombo();
        jPanel6.setVisible(true);
        //MyComboBoxModel mymodel=new MyComboBoxModel();
        //jPanel10.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        feeCombo = new javax.swing.JComboBox<>();
        yearCombo = new javax.swing.JComboBox<>();
        rollNoCombo = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnViewInfo = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblNoti = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtFee = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDeadline = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDeleteforStudent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRollno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        comboYear = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        reportCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        txtExcelName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtFeeforInfo = new javax.swing.JTextField();
        txtDeadlineforInfo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnStudents = new javax.swing.JButton();
        btnFees = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName(""); // NOI18N

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setMaximumSize(new java.awt.Dimension(1374, 720));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(1374, 720));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(1179, 95));
        jPanel2.setName(""); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1179, 95));

        jLabel4.setFont(new java.awt.Font("Calibri", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Welcome to Student Fee Payment System");
        jLabel4.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));
        jPanel3.setMaximumSize(new java.awt.Dimension(1179, 625));
        jPanel3.setPreferredSize(new java.awt.Dimension(1179, 625));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setMaximumSize(new java.awt.Dimension(807, 553));
        jPanel4.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(1179, 625));
        jPanel5.setPreferredSize(new java.awt.Dimension(1179, 625));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Type of Fee");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Year");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Roll No");

        feeCombo.setBorder(null);
        feeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                feeComboItemStateChanged(evt);
            }
        });
        feeCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                feeComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        feeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeComboActionPerformed(evt);
            }
        });

        yearCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                yearComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        yearCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboActionPerformed(evt);
            }
        });

        rollNoCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                rollNoComboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        rollNoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollNoComboActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 102, 102));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnViewInfo.setBackground(new java.awt.Color(0, 102, 102));
        btnViewInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInfo.setText("View Info");
        btnViewInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInfoActionPerformed(evt);
            }
        });

        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Name");

        lblNoti.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNoti.setForeground(new java.awt.Color(255, 51, 51));
        lblNoti.setText("The deadline is passed !");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNoti, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(feeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(yearCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(rollNoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(btnViewInfo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(534, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollNoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewInfo)
                    .addComponent(btnSave))
                .addGap(96, 96, 96)
                .addComponent(lblNoti, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, "card2");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Type of Fee");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Fee");

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(0, 102, 102));
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 102, 102));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Deadline");

        txtDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeadlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCreate)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel1))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtType)
                            .addComponent(txtFee, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(txtDeadline))))
                .addGap(32, 32, 32)
                .addComponent(btnDelete)
                .addContainerGap(462, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(211, 211, 211)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, "card3");

        btnInsert.setBackground(new java.awt.Color(0, 102, 102));
        btnInsert.setForeground(new java.awt.Color(255, 255, 255));
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDeleteforStudent.setBackground(new java.awt.Color(0, 102, 102));
        btnDeleteforStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteforStudent.setText("Delete");
        btnDeleteforStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteforStudentActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Year");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("RollNo");

        comboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th", "H1", "H2", "H3", "Qualify" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsert)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(btnDeleteforStudent))
                .addGap(53, 53, 53)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdate)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboYear, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(txtRollno, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRollno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert)
                            .addComponent(btnUpdate))
                        .addGap(43, 43, 43)
                        .addComponent(btnDeleteforStudent))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel9, "card4");

        jPanel10.setForeground(new java.awt.Color(0, 102, 102));
        jPanel10.setPreferredSize(new java.awt.Dimension(806, 553));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Year");

        btnPrint.setBackground(new java.awt.Color(0, 102, 102));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnView.setBackground(new java.awt.Color(0, 102, 102));
        btnView.setText("OK");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnExcel.setBackground(new java.awt.Color(0, 104, 104));
        btnExcel.setText("Export to Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        jLabel10.setText("File Name");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnView)
                        .addGap(45, 45, 45)
                        .addComponent(btnPrint))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExcelName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcel))))
                .addGap(78, 78, 78)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(reportCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnView)
                            .addComponent(btnPrint))
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(txtExcelName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(btnExcel)))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel10, "card5");

        jLabel16.setText("Deadline");

        jLabel18.setText("Fee");

        btnOk.setBackground(new java.awt.Color(0, 102, 102));
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(86, 86, 86)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDeadlineforInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(txtFeeforInfo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(827, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtFeeforInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtDeadlineforInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnOk)
                .addContainerGap(368, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel11, "card4");

        jPanel3.add(jPanel4, "card2");

        jDesktopPane1.setMaximumSize(new java.awt.Dimension(187, 786));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(187, 786));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setName(""); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setName(""); // NOI18N

        btnStudents.setBackground(new java.awt.Color(0, 102, 102));
        btnStudents.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnStudents.setText("Students");
        btnStudents.setName("btnStudent"); // NOI18N
        btnStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentsActionPerformed(evt);
            }
        });

        btnFees.setBackground(new java.awt.Color(0, 102, 102));
        btnFees.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFees.setForeground(new java.awt.Color(255, 255, 255));
        btnFees.setText("Fees");
        btnFees.setName("btnFee"); // NOI18N
        btnFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeesActionPerformed(evt);
            }
        });

        btnDashboard.setBackground(new java.awt.Color(0, 102, 102));
        btnDashboard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.setName("btnDashboard"); // NOI18N
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(0, 102, 102));
        btnReport.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setText("Report");
        btnReport.setName("btnReport"); // NOI18N
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(0, 102, 102));
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFees, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(btnLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JComboBox getComboBox()
    {
        return feeCombo;
    }
    public void getConnection()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void feeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeComboActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        //jPanel5.setVisible(true);
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        
        jPanel4.add(jPanel5);
        jPanel4.repaint();
        jPanel4.revalidate();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeesActionPerformed
        // TODO add your handling code here:
        //jPanel5.setVisible(false);
        //jPanel7.setVisible(true);
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        
        jPanel4.add(jPanel7);
        jPanel4.repaint();
        jPanel4.revalidate();
    }//GEN-LAST:event_btnFeesActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        /*try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="create table "+txtType.getText()+"(rollNo varchar(20),name varchar(50),year varchar(20),fee varchar(30),status varchar(30))";
            pst=cnn.prepareStatement(sql);
            int rs=pst.executeUpdate();
            if(rs>=0)
            {
                JOptionPane.showMessageDialog(null,"Success");
                //feeCombo.addItem(txtType.getText());
            }
            else
                JOptionPane.showMessageDialog(null, "Fail");
            
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }*/
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            createNew();
            String sql="alter table students add column "+txtType.getText()+" varchar(50)";
            pst=cnn.prepareStatement(sql);
            int rs=pst.executeUpdate();
            if(rs>=1)
            {
                JOptionPane.showMessageDialog(null,"Success");
                insertStatus();
                //feeCombo.addItem(txtType.getText());
            }
            else
                JOptionPane.showMessageDialog(null, "Fail");
            
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
            feeCombo.addItem(txtType.getText());
    }//GEN-LAST:event_btnCreateActionPerformed
    public void insertStatus()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String s="update students set "+txtType.getText()+"='0'";
            pst=cnn.prepareStatement(s);
            int r=pst.executeUpdate();
            if(r>=1)
            {
                JOptionPane.showMessageDialog(null,"Success");
            }
            else
                JOptionPane.showMessageDialog(null, "Fail");

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        delete();
        try{
            getConnection();
            /*Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);*/
            String sql="alter table students drop column "+txtType.getText();
            pst=cnn.prepareStatement(sql);
            int rs=pst.executeUpdate();
            if(rs>=0)
            {
                JOptionPane.showMessageDialog(null, "Success");
                
            }
            else
                JOptionPane.showMessageDialog(null, "Fail");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        feeCombo.removeItem(txtType.getText());
    }//GEN-LAST:event_btnDeleteActionPerformed
    public void delete()
    {
        try{
            getConnection();
            String sql="delete from feeinfo where feeType='"+txtType.getText()+"'";
            pst=cnn.prepareStatement(sql);
            int rs=pst.executeUpdate();
            if(rs>=0)
                JOptionPane.showMessageDialog(null,"Success");
            else
                JOptionPane.showMessageDialog(null, "Fail");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentsActionPerformed
        // TODO add your handling code here:
        //jPanel5.setVisible(false);
        //jPanel7.setVisible(false);
        //jPanel9.setVisible(true);
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        
        jPanel4.add(jPanel9);
        jPanel4.repaint();
        jPanel4.revalidate();
        DefaultTableModel dm=new UpdateTable().getData();
        jTable1.setModel(dm);
    }//GEN-LAST:event_btnStudentsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:{
        String fee=getFee().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select "+feeCombo.getSelectedItem()+" from students where rollNo='"+rollNoCombo.getSelectedItem().toString()+"'";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            while(res.next())
            {
            String r=res.getString(feeCombo.getSelectedItem().toString());
            if(r.equalsIgnoreCase("0"))
             {
                Class.forName("com.mysql.jdbc.Driver");
                cnn=DriverManager.getConnection(url);
                String upd="update students set "+feeCombo.getSelectedItem().toString()+"='"+fee+"' where rollNo='"+rollNoCombo.getSelectedItem().toString()+"'";
                pst=cnn.prepareStatement(upd);
                int result=pst.executeUpdate();
                if(result>=1)
                {
                    JOptionPane.showMessageDialog(null, "Save success");
                }
                else
                    JOptionPane.showMessageDialog(null, "Fail");
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Already Paid");
            }
            }
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_btnSaveActionPerformed
    public void check()
    {
        String r="";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select "+feeCombo.getSelectedItem().toString()+" from students where rollNo='"+rollNoCombo.getSelectedItem().toString()+"'";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            if(res.next())
                JOptionPane.showMessageDialog(null, "Already Paid");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void txtDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeadlineActionPerformed

    private void btnViewInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInfoActionPerformed
        // TODO add your handling code here:
        /*String newCombo;
            newCombo = feeCombo.getSelectedItem().toString();
        feeInfo info=new feeInfo(newCombo);
        info.setVisible(true);
        //feeInformation fee=new feeInformation();*/
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        
        jPanel4.add(jPanel11);
        jPanel4.repaint();
        jPanel4.revalidate();
        getFee();
        txtFeeforInfo.setText(getFee());

        getDeadline();
    }//GEN-LAST:event_btnViewInfoActionPerformed
     public String getFee()
    {
        String c=feeCombo.getSelectedItem().toString();
        String fee="";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select fee from feeinfo where feeType=?";
            pst=cnn.prepareStatement(sql);
            pst.setString(1, c);
            res=pst.executeQuery();
            if(res.next())
            {
                fee=res.getString("fee");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        return fee;
    }
    public void getDeadline()
    {
        String c=feeCombo.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select deadline from feeinfo where feeType=?";
            pst=cnn.prepareStatement(sql);
            pst.setString(1,c);
            res=pst.executeQuery();
            String deadline="";
            if(res.next())
            {
                deadline=res.getString("deadline");
            }
            txtDeadlineforInfo.setText(deadline);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="insert into students(rollNo,name,year) values('"+txtRollno.getText()+"','"+txtName.getText()+"','"+comboYear.getSelectedItem().toString()+"')";
            pst=cnn.prepareStatement(sql);
            int r=pst.executeUpdate();
            
            if(r>=1)
            {
                JOptionPane.showMessageDialog(null, "Success");
                
            }
            else
                JOptionPane.showMessageDialog(null, "Fail");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        Unpaid();
        DefaultTableModel dm=new UpdateTable().getData();
        jTable1.setModel(dm);
        //yearCombo.add(comboYear.getSelectedItem().toString());
    }//GEN-LAST:event_btnInsertActionPerformed
    public void Unpaid()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select column_name from information_schema.columns where table_name='students' and table_schema='payment'";
            //String sql="select table_name from information_schema.tables where table_schema='payment'";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            int size=0;
            while(res.next())
            {
                //String fee=res.getString("column_name");
                //feeCombo.addItem(fee);
                //size=res.getRow();
                
                /*for(int i=4;i<=size;i++)
                {
                    String fee=res.getString("column_name");
                    feeCombo.addItem(fee);
                }*/
                //String name=res.getString("column_name");
                size++;
                if(size>3)
                {
                    try{
                        Class.forName("com.mysql.jdbc.Driver");
                        cnn=DriverManager.getConnection(url);
                        String s="update students set "+res.getString("column_name")+"='0' where rollNo='"+txtRollno.getText()+"'";
                        pst=cnn.prepareStatement(s);
                        int r=pst.executeUpdate();
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            }
            
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="update students set name='"+txtName.getText()+"', year='"+comboYear.getSelectedItem().toString()+"' where rollNo='"+txtRollno.getText()+"'";
            pst=cnn.prepareStatement(sql);
            int r=pst.executeUpdate();
            //DefaultTableModel model=(DefaultTableModel)table.getModel();
            if(r>=1)
            {
                JOptionPane.showMessageDialog(null, "Success");
                
            }
            else
                JOptionPane.showMessageDialog(null, "Fail");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        DefaultTableModel dm=new UpdateTable().getData();
        jTable1.setModel(dm);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteforStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteforStudentActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="delete from students where rollNo='"+txtRollno.getText()+"'";
            pst=cnn.prepareStatement(sql);
            int r=pst.executeUpdate();
            
            if(r>=1)
            {
                JOptionPane.showMessageDialog(null, "Success");
            }
            else
                JOptionPane.showMessageDialog(null, "Fail");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        DefaultTableModel dm=new UpdateTable().getData();
        jTable1.setModel(dm);
    }//GEN-LAST:event_btnDeleteforStudentActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        //jPanel5.setVisible(false);
        //jPanel7.setVisible(false);
        //jPanel9.setVisible(false);
        //jPanel10.setVisible(true);
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        
        jPanel4.add(jPanel10);
        jPanel4.repaint();
        jPanel4.revalidate();
        //viewReport();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select year,count(year) from students group by year having count(year)>1";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            
            while(res.next())
            {
                String year=res.getString("year");
                reportCombo.addItem(year);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        DefaultTableModel dm=new UpdateTable().getData();
        jTable2.setModel(dm);
    }//GEN-LAST:event_btnReportActionPerformed

    private void yearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearComboActionPerformed

    private void yearComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_yearComboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String display=yearCombo.getSelectedItem().toString();
        rollNoCombo.removeAllItems();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select rollNo from students where year=?";
            pst=cnn.prepareStatement(sql);
            pst.setString(1, display);
            res=pst.executeQuery();
            while(res.next())
            {
                String add=res.getString("rollNo");
                rollNoCombo.addItem(add);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_yearComboPopupMenuWillBecomeInvisible

    private void rollNoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollNoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollNoComboActionPerformed

    private void rollNoComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_rollNoComboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String display=rollNoCombo.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select name from students where rollNo=?";
            pst=cnn.prepareStatement(sql);
            pst.setString(1, display);
            res=pst.executeQuery();
            String name="";
            if(res.next())
            {
                name=res.getString("name");
            }
            txtname.setText(name);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_rollNoComboPopupMenuWillBecomeInvisible

    private void feeComboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_feeComboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        String feeType=feeCombo.getSelectedItem().toString();
        Date deadline = null;
        
                    try{
                        Class.forName("com.mysql.jdbc.Driver");
                        cnn=DriverManager.getConnection(url);
                        String r="select deadline from feeinfo where feeType=?";
                        pst=cnn.prepareStatement(r);
                        pst.setString(1,feeType );
                        res=pst.executeQuery();
                        while(res.next())
                        {
                            deadline=res.getDate("deadline");
                        }
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(null, e);
                    }
                    DateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
                    //Date date=new Date();
                    //String text=
                    if(deadline.before(new Date()))
                    {
                        lblNoti.setVisible(true);
                    }
                    else if(deadline.after(new Date()))
                       lblNoti.setVisible(false);
    }//GEN-LAST:event_feeComboPopupMenuWillBecomeInvisible

    private void feeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_feeComboItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_feeComboItemStateChanged

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        
        jPanel4.add(jPanel5);
        jPanel4.repaint();
        jPanel4.revalidate();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        /*String roll=reportCombo.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select * from students where rollNo='"+roll+"'";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            while(res.next())
            {
                DisplayResultSetforReport(res);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }*/
        MessageFormat header=new MessageFormat("Report");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try{
            jTable2.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        /*Document document;
        document = new Document(PageSize.A4.rotate()) {};
        try{
            PdfWriter writer=PdfWriter.getInstance(document, new FileOutputStream("Report.pdf"));
            document.open();
            PdfContentByte cb=writer.getDirectContent();
            cb.saveState();
            Graphics2D g2=cb.createGraphicsShapes(500, 500);
            Shape oldClip=g2.getClip();
            g2.clipRect(0, 0, 500, 500);
            table.print(g2);
            g2.setClip(oldClip);
            g2.dispose();
            cb.restoreState();
            //document.add(table);
            document.close();
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }*/
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        try{
            getConnection();
            String sql="select * from students where year='"+reportCombo.getSelectedItem().toString()+"'";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            //while(res.next())
            //{
                new ViewTable(res);    
            //}
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        DefaultTableModel dm=new ViewTable(res).getView();
        jTable2.setModel(dm);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        Login login=new Login();
        MainPage.this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
        try{
            HSSFWorkbook fworkbook=new HSSFWorkbook();
            HSSFSheet fSheet=fworkbook.createSheet("Sheet 1");
            HSSFFont font=fworkbook.createFont();
            File file=new File("E:\\"+txtExcelName.getText()+".xls");
            HSSFCellStyle style=fworkbook.createCellStyle();
            font.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
            
            //DefaultTableModel model=new UpdateTable().getData();
            //jTable2.setModel(model);
            DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
            TableColumnModel tcm=jTable2.getColumnModel();
            HSSFRow frow=fSheet.createRow((short)0);
            for(int j=0;j<tcm.getColumnCount();j++)
            {
                HSSFCell cell=frow.createCell((short)j);
                cell.setCellValue(tcm.getColumn(j).getHeaderValue().toString());
            }
            
            for(int i=0;i<model.getRowCount();i++)
            {
                HSSFRow row=fSheet.createRow((short)i+1);
                for(int j=0;j<model.getColumnCount();j++)
                {
                    HSSFCell cell=row.createCell((short)j);
                    cell.setCellValue(model.getValueAt(i, j).toString());
                    cell.setCellStyle(style);
                }
            }
            FileOutputStream fileOutputStream;
            fileOutputStream=new FileOutputStream(file);
            BufferedOutputStream bos=new BufferedOutputStream(fileOutputStream);
            fworkbook.write(bos);
            bos.close();
            fileOutputStream.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnExcelActionPerformed
    
    private void rollNoCombo()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select * from students where year='"+yearCombo.getSelectedItem().toString()+"'";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            
            while(res.next())
            {
                String rollNo=res.getString("rollNo");
                rollNoCombo.addItem(rollNo);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
   private void yearCombo()
    {
        /*try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select year,count(year) from students group by year having count(year)>1";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            
            while(res.next())
            {
                String year=res.getString("year");
                yearCombo.addItem(year);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }*/
        yearCombo.addItem("1st");
        yearCombo.addItem("2nd");
        yearCombo.addItem("3rd");
        yearCombo.addItem("4th");
        yearCombo.addItem("H1");
        yearCombo.addItem("H2");
        yearCombo.addItem("H3");
        yearCombo.addItem("Qualify");
    }
    private void feeCombo()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="select column_name from information_schema.columns where table_name='students' and table_schema='payment'";
            //String sql="select table_name from information_schema.tables where table_schema='payment'";
            pst=cnn.prepareStatement(sql);
            res=pst.executeQuery();
            int size=0;
            while(res.next())
            {
                //String fee=res.getString("column_name");
                //feeCombo.addItem(fee);
                //size=res.getRow();
                
                /*for(int i=4;i<=size;i++)
                {
                    String fee=res.getString("column_name");
                    feeCombo.addItem(fee);
                }*/
                String fee=res.getString("column_name");
                size++;
                if(size>3)
                {
                    feeCombo.addItem(fee);
                }
            }
            
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    }
    public void createNew()
    {
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cnn=DriverManager.getConnection(url);
            String sql="insert into feeinfo(feeType,fee,deadline) values('"+txtType.getText()+"','"+txtFee.getText()+"','"+txtDeadline.getText()+"')";
            pst=cnn.prepareStatement(sql);
            int result=pst.executeUpdate();
            if(result>=0)
                JOptionPane.showMessageDialog(null, "Insert success");
            else
                JOptionPane.showMessageDialog(null, "Insert fail");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public Date getDate()
    {
        DateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd");
        Date date=new Date();
        return date;
    }
    
    public String getYear()
    {
        return reportCombo.getSelectedItem().toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteforStudent;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnFees;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStudents;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JButton btnViewInfo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> comboYear;
    public javax.swing.JComboBox<String> feeCombo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblNoti;
    private javax.swing.JComboBox<String> reportCombo;
    public javax.swing.JComboBox<String> rollNoCombo;
    private javax.swing.JTextField txtDeadline;
    private javax.swing.JTextField txtDeadlineforInfo;
    private javax.swing.JTextField txtExcelName;
    private javax.swing.JTextField txtFee;
    private javax.swing.JTextField txtFeeforInfo;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRollno;
    private javax.swing.JTextField txtType;
    private javax.swing.JTextField txtname;
    private javax.swing.JComboBox<String> yearCombo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        
    }
}
